// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TripLog.Models;

namespace TripLog.Migrations
{
    [DbContext(typeof(TripContext))]
    [Migration("20211026005039_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TripLog.Models.TripsLog", b =>
                {
                    b.Property<int>("TripsLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AcommEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AcommPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Acommodation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dest")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("ToDo1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToDo2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToDo3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TripsLogId");

                    b.ToTable("Trips");
                });
#pragma warning restore 612, 618
        }
    }
}
